; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = direct
lib_deps = 
	northernwidget/DS3231@^1.1.2
	adafruit/DHT sensor library@^1.4.6
	bblanchon/ArduinoJson @ ^6.21.0 ; JSON-Parsing und Serialisierung
build_flags = 
	-D SPI_MOSI=23
	-D SPI_CLK=18
	-D SPI_MISO=19
	-D MEMORY_0_CS=5
	-D I2C_SDA=21
	-D I2C_SCL=22
  -D DHTPIN_0=33
  -D DHTPIN_1=25
  -D DHTPIN_2=26
  -D DHTPIN_3=27
  -D ANALOG_IN_0=35
[env:native]
platform = native
test_framework = googletest
build_flags = -I test/stubs
build_src_filter = -<*> +<HttpUtils.cpp>